export { aperture } from './aperture.js'
export { initLoom, resizeLoom, getLoomState } from './init.js'
export { refreshLoom } from './refresh.js'
export { scrollThread, scrollThreadToVoice } from './scroll.js'
export { setHighlight, clearHighlight } from './highlight.js'
export { setResonance } from './resonance.js'
export { setDiagHook, isPhantomActive, triggerPhantomHover } from './phantom.js'
export { renderLoom, advanceLoom, paintLoom } from './render/frame.js'
export { getLoomSnapshot, getLastFrameHitVoiceIdAt, findThreadIndexForFamily } from './state.js'
export { enterLoomView, exitLoomView, isLoomViewActive, getCurrentLoomSeed, recenterLoomView } from './loom-view.js'
export type { ApertureConfig, LoomNode, LoomSnapshot, LoomThreadSnapshot, LoomTree, MouseState } from './types.js'
